FROM node:20-alpine

WORKDIR /app

# Yarn v3を使用
RUN corepack enable && corepack prepare yarn@3.6.4 --activate

COPY package.json yarn.lock ./
RUN yarn config set nodeLinker node-modules && yarn install --frozen-lockfile

EXPOSE 5173

# Vite development server
CMD ["yarn", "dev", "--host", "0.0.0.0", "--port", "5173"]