services:
  - type: web
    name: jibun-chara-frontend
    env: static
    buildCommand: yarn install && yarn build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://jubun-chara-backend.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
