services:
  - type: web
    name: jubun-chara-backend
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec rails db:migrate && bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jubun-chara-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: FRONTEND_URL
        value: https://jibun-chara.onrender.com
      - key: ALLOWED_ORIGINS
        value: http://localhost:5173,https://jibun-chara.onrender.com
    autoDeploy: true

databases:
  - name: jubun-chara-db
    databaseName: jibun_chara_production
    user: postgres 